# Docker Compose for Production deployment
version: "3.8"

networks:
  api-network:
    driver: bridge

services:
  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-gateway-prod
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - PORT=10000
    env_file:
      - .env.production
    ports:
      - "10000:10000"
    networks:
      - api-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:10000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
