version: "3.8"

networks:
  api-network:
    driver: bridge

services:
  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-gateway-dev
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - PORT=5257
    env_file:
      - .env
    ports:
      - "5257:5257"
    networks:
      - api-network
    volumes:
      - ./.env:/app/.env:ro
      - app-network
    depends_on:
      - text-generate-app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5257/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  text-generate-app:
    build: ../text-generate-services
    container_name: text-generate-app
    environment:
      APP_ENV: production
      APP_DEBUG: "false"
      APP_URL: http://text-generate-app:8000
      SERVER_PORT: 8000
    volumes:
      - ../text-generate-services:/var/www
    ports:
      - "8000:8000"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/system/server-info"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
