# Render deployment configuration
services:
  - type: web
    name: api-gateway-aio
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: free
    region: singapore
    branch: main
    healthCheckPath: /health
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ASPNETCORE_URLS
        value: http://0.0.0.0:10000
      - key: PORT
        value: "10000"
      - key: TEXT_GENERATE_SERVICE_URL
        value: https://text-generate-services.onrender.com
    scaling:
      minInstances: 1
      maxInstances: 1
